<?php $qvCf = Mage::getStoreConfig('quickview'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

 <div class="product-quickview">
	<?php echo $this->getChildHtml('media') ?>
	<div id="tabquickshowcontainer">
		<?php if(@$qvCf['viewsetting']['enabledetail'] || @$qvCf['viewsetting']['enablereview']){ ?>
		<div class="qvtabhead">
			<a class="tabquickviewcontrol highlight" href="#quickview1"><?php echo $this->__('Summary') ?></a>
		<?php } ?>
		<?php if(@$qvCf['viewsetting']['enabledetail']){ ?>
			<a class="tabquickviewcontrol" href="#quickview2"><?php echo $this->__('Detail') ?></a>
		<?php } ?>
		<?php if(@$qvCf['viewsetting']['enablereview']){ ?>
			<a class="tabquickviewcontrol" href="#quickview3"><?php echo $this->__('Reviews') ?></a>
		<?php } ?>
		
		<?php if(@$qvCf['viewsetting']['enabledetail'] || @$qvCf['viewsetting']['enablereview']){ ?> <div style="clear:both;"></div></div> <?php } ?>
	
		<div class="tabquickshow" id="quickview1">
			<div class="product-name"><h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1></div>
			<?php // echo $this->getReviewsSummaryHtml($_product, false, true)?>
			
				<p class="price">
					<?php if($_product->getSpecialPrice()): ?>
						WAS <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>
						<span class="special-price">
						NOW <?php echo Mage::helper('core')->currency($_product->getSpecialPrice(), true, false); ?>
						</span>
					<?php else: ?>
						<?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?>
					<?php endif; ?>
				</p>
							
			<div class="quickviewcontent">			
				<?php if ($_product->getShortDescription()):?>
					<div class="short-description">
<!-- 						<h2><?php echo $this->__('Quick Overview') ?></h2> -->
						<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					</div>
				<?php endif;?>
				
				<?php echo $this->getChildHtml('product_type_data') ?>
				<?php // echo $this->getTierPriceHtml() ?>


			</div>
			<div class="clearer"></div>
			
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(@$qvCf['viewsetting']['footerblockid'])->toHtml() ?> 
		</div>
		
		
		
		<div class="tabquickshow" id="quickview2" style="display:none;">
			<div class="quickviewcontent">
				<?php echo $this->getChildHtml('description') ?>
				<br/>
				<?php echo $this->getChildHtml('additional') ?>
			 </div>
		</div>
		
		
		
		<div class="tabquickshow"  id="quickview3" style="display:none;">
			<div class="quickviewcontent">

				<?php //echo $this->getChildHtml('upsell_products') ?>
				<?php echo $this->getChildHtml('reviews') ?>
				<?php //echo $this->getChildHtml('product_additional_data') ?>
			 </div>
		</div>
		
		<div class="qvformaddtocart">
			<?php // echo $this->getChildHtml('price') ?>
			<form action="<?php  echo $this->getAddToCartUrl($_product); ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

				<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
				<input type="hidden" name="related_product" id="related-products-field" value="" />
				
				<?php if(@$qvCf['viewsetting']['enableaddtocart']){ ?>
				<?php if (!$this->hasOptions()  || @$qvCf['viewsetting']['qvshowoption'] == 0){ ?>
					<div class="add-to-box">
						<?php if($_product->isSaleable()): ?>
							<?php echo $this->getChildHtml('addtocart') ?>
						<?php endif; ?>
						
					</div>
				<?php }else{ ?>

				
					<?php //if ($_product->isSaleable() && $this->hasOptions()):?>
						<?php echo $this->getChildChildHtml('container1', '', true, true); ?>
						<?php 
							$string =  $this->getChildChildHtml('container2', '', true, true);
							//echo  strip_tags($string, '<input>,<div><p><a><dl><dt><dd><button><img><span>');
							if($string){
								//$string = str_replace(array('<script', '</script>', 'type="text/javascript"'), array('<div style="display:none;"', '</div>', ''), $string);
								//echo preg_replace('/<div[^>]*>.*?<\/div>/i', '', $string);
								echo $string;
							}
							//echo $string =   preg_replace("/<script[^>]*>.*?script>/i", "", $string);
						?>
					<?php } ?>
					
				<?php } ?>
										<a class="qvmoredetail" href="<?php echo $_product->getProductUrl();?>"><?php echo $this->__('View product details page') ?></a>
				</form>	

			</div>
			
				<script type="text/javascript">
				//<![CDATA[
				
					var productAddToCartForm = new VarienForm('product_addtocart_form');
					productAddToCartForm.submit = function(button, url) {
						if (this.validator.validate()) {
							var form = this.form;
							var oldUrl = form.action;

							if (url) {
							   form.action = url;
							}
							var e = null;
							try {
								this.form.submit();
							} catch (e) {
							}
							this.form.action = oldUrl;
							if (e) {
								throw e;
							}

							if (button && button != 'undefined') {
								button.disabled = true;
							}
						}
					}.bind(productAddToCartForm);

					productAddToCartForm.submitLight = function(button, url){
						if(this.validator) {
							var nv = Validation.methods;
							delete Validation.methods['required-entry'];
							delete Validation.methods['validate-one-required'];
							delete Validation.methods['validate-one-required-by-name'];
							// Remove custom datetime validators
							for (var methodName in Validation.methods) {
								if (methodName.match(/^validate-datetime-.*/i)) {
									delete Validation.methods[methodName];
								}
							}

							if (this.validator.validate()) {
								if (url) {
									this.form.action = url;
								}
								this.form.submit();
							}
							Object.extend(Validation.methods, nv);
						}
					}.bind(productAddToCartForm);
				//]]>
				</script>
	</div>
	<div class="clearer"></div>
	
</div>
<!--
<?php if(@$qvCf['viewsetting']['enablefooter']){ ?>

<div class="quickview_footer">

	<div style="clear:both;"></div>
</div>
<?php } ?>
-->
