<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <div class="box-up-sell-title">
       <h3><?php echo $this->__('You Might Also Like') ?></h3>
    </div>
    <ul class="row products-grid" id="upsell-product-table">
    <?php $this->setColumnCount(3); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php // for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <li class="span4 item">
            <?php if($_link=$this->getIterableItem()): ?>
				<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" class="product-image">
                    <span class="view-overlay">View</span>
                    <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(300); ?>" width="300" height="300" alt="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" />
				</a>
                <?php
                $price_html = "<span class=\"price\">";
                if($_link->getSpecialPrice()):
                    $price_html .= Mage::helper('core')->currency($_link->getPrice(), true, false);
                    $price_html .= "<span class=\"special-price\">";
                    $price_html .= Mage::helper('core')->currency($_link->getSpecialPrice(), true, false);
                    $price_html .= "</span>";
                else:
                    $price_html .= Mage::helper('core')->currency($_link->getPrice(), true, false);
                endif;
                $price_html .= "</span>";
                ?>

                <?php $product_name = strip_tags($_link->getName()) ?>

                <?php if(strlen($product_name)>45) : ?>
                    <?php $product_name = substr($product_name,0,90); ?>
                    <a href="<?php echo $_link->getProductUrl() ?>" class="product-name"><?php echo $product_name; ?>&#133; </a>
                    <?php echo $price_html; ?>
                <?php else : ?>
                    <a href="<?php echo $_link->getProductUrl() ?>" class="product-name"><?php echo $product_name ?> </a>
                    <?php echo $price_html; ?>

                <?php endif; ?>
			<?php endif;?>
        </li>
        <?php endfor; ?>
    <?php// endfor; ?>
    </ul>
</div>
<?php endif ?>
