<?php
// $Id$

/**
 * @file
 * Provides examples of JavaScript additions to form elements.
 */

/**
 * Implementation of hook_menu().
 */
function jsforms_menu() {
  $items = array();

  $items['js-forms'] = array(
    'title' => 'JavaScript Forms example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jsforms_example'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function jsforms_example() {
  $form = array();

  $form['group'] = array(
    '#type' => 'fieldset',
    '#title' => t('A group of fields'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['group']['username'] = array(
    '#type' => 'textfield',
    '#title' => t('User name'),
    '#autocomplete_path' => 'user/autocomplete',
  );

  $form['group']['textarea'] = array(
    '#type' => 'textarea',
    '#title' => t('Sample textarea'),
    '#resizable' => FALSE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}
