<?php
// $Id$

/**
 * @file
 * Validates username and email address during registration.
 */

/**
 * Implementation of hook_menu().
 */
function regval_menu() {
  $items = array();

  $items['regval/name'] = array(
    'page callback' => 'regval_check_name',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['regval/mail'] = array(
    'page callback' => 'regval_check_mail',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function regval_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_register') {
    drupal_add_css(drupal_get_path('module', 'regval') . '/regval.css');

    // The location of fields may change depending on profile.module.
    if (isset($form['account'])) {
      $account_form = &$form['account'];
    }
    else {
      $account_form = &$form;
    }

    $suffix = isset($account_form['name']['#suffix']) ? $account_form['name']['#suffix'] : '';
    $account_form['name']['#suffix'] = $suffix . '<div id="regval-name-wrapper"></div>';
    $account_form['name']['#ahah'] = array(
      'path' => 'regval/name',
      'wrapper' => 'regval-name-wrapper',
      'progress' => 'none',
      'event' => 'blur',
    );
    $suffix = isset($account_form['mail']['#suffix']) ? $account_form['mail']['#suffix'] : '';
    $account_form['mail']['#suffix'] = $suffix . '<div id="regval-mail-wrapper"></div>';
    $account_form['mail']['#ahah'] = array(
      'path' => 'regval/mail',
      'wrapper' => 'regval-mail-wrapper',
      'progress' => 'none',
      'event' => 'blur',
    );
  }
}

/**
 * Menu callback for AHAH requests.
 */
function regval_check_name() {
  global $user;

  $name = $_POST['name'];
  $output = '';

  if (!empty($name)) {
    $errors = array();
    // Validate user name.
    $error = user_validate_name($name);
    if ($error) {
      $errors[] = $error;
    }
    $exists = db_result(db_query("SELECT uid FROM {users} WHERE name = '%s'", $name));
    if ($exists) {
      $errors[] = t('This username already exists.');
    }
    if (count($errors)){
      $output .= theme('image', 'misc/watchdog-error.png', t('error')) . ' ' . implode(' ', $errors);
    }
    else {
      $output .= theme('image', 'misc/watchdog-ok.png', t('ok')) . ' ' . t('Username is available.');
    }
  }

  drupal_json(array('result' => TRUE, 'data' => $output));
}

/**
 * Menu callback for AHAH requests.
 */
function regval_check_mail() {
  global $user;

  $mail = $_POST['mail'];
  $output = '';

  if (!empty($mail)) {
    $errors = array();
    // Validate user name.
    $error = !valid_email_address($mail);
    if ($error) {
      $errors[] = t('Invalid email address.');
    }
    $exists = db_result(db_query("SELECT uid FROM {users} WHERE mail = '%s'", $mail));
    if ($exists) {
      $errors[] = t('This email address is already registered.');
    }
    if (count($errors)){
      $output .= theme('image', 'misc/watchdog-error.png', t('error')) . ' ' . implode(' ', $errors);
    }
    else {
      $output .= theme('image', 'misc/watchdog-ok.png', t('ok')) . ' ' . t('Email address is valid.');
    }
  }

  drupal_json(array('result' => TRUE, 'data' => $output));
}
