<?php

/**
 * @file
 * Databasics module.
 */

/**
 * Implements hook_menu().
 */
function databasics_menu() {
  $items = array();

  $items['user/%user/databasics'] = array(
    'title' => 'Page Views',
    'description' => 'Listing of page views by user.',
    'page callback' => 'databasics_user_page',
    'page arguments' => array(1),
    'access callback' => 'databasics_access_callback',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/system/databasics'] = array(
    'title' => 'Databasics settings',
    'description' => 'Configuration for the databasics module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('databasics_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'databasics.admin.inc',
  );

  return $items;
}

/**
 * Only allow users to see the page views for their own account or if they are
 * an administrator.
 */
function databasics_access_callback($account) {
  global $user;

  return $user->uid == $account->uid || user_access('access site reports');
}

/**
 * Implements hook_node_view().
 */
function databasics_node_view($node, $view_mode = 'full') {
  if ($view_mode == 'full') {
    global $user;

    // Load up the current record.
    $record = databasics_get_record($node->nid, $user->uid);

    // If there is no record, create one.
    if (!$record) {
      $record = new stdClass();
      $record->nid = $node->nid;
      $record->uid = $user->uid;
      $record->view_count = 0;
      $record->last_viewed = REQUEST_TIME;
    }

    // Increment the current count.
    $record->view_count++;
    $record->last_viewed = REQUEST_TIME;

    // Save the record.
    databasics_set_record($record);

    $message = variable_get('databasics_message', 'You have viewed this page.');

    // Add the view count information to the node content.
    $node->content['node_views'] = array(
      '#markup' => $message,
      '#weight' => 10,
    );
  }
}

/**
 * Get the record.
 *
 * @param int $nid
 *   The node id.
 * @param int $uid
 *   The user id.
 * @return mixed
 *   The stdClass record, or FALSE if no record exists.
 */
function databasics_get_record($nid, $uid) {
  $query = db_select('databasics')
    ->fields('databasics')
    ->condition('nid', $nid)
    ->condition('uid', $uid);

  return $query->execute()->fetch();
}

/**
 * Save a record.
 *
 * @param stdClass $record
 *   The record to save.
 */
function databasics_set_record(stdClass $record) {
  // Use a Merge query. A Merge query is a combination of an Insert query and
  // an Update query, so if the record already exists, it will be updated.
  // @see http://drupal.org/node/310085
  db_merge('databasics')
    ->key(array('nid' => $record->nid))
    ->key(array('uid' => $record->uid))
    ->fields((array) $record)
    ->execute();
}

/**
 * Display a tab on the user/N/databasics page which lists all the pages on the
 * site that the user has viewed and the total number of times each page has
 * been viewed.
 *
 * @param stdClass $account
 *   The user account.
 * @return
 *   A themed table of the results.
 */
function databasics_user_page(stdClass $account) {
  $rows = array();

  // Get information about all the pages the user has viewed
  $query = db_select('databasics', 'd')
    ->condition('d.uid', $account->uid);

  // Joins return the alias of the table, so we can't chain it.
  $query->innerJoin('node', 'n', 'n.nid = d.nid');

  // Load up all the fields from the databasics table.
  $query->fields('d');

  // You can use addField() to add single fields. This is especially useful if
  // you need to alias a field, but keep in mind you cannot chain these together.
  $query->addField('n', 'nid');
  $query->addField('n', 'title');

  // Iterate over the results returned from the database and collect the
  // information in an array.
  $results = $query->execute();
  foreach ($results as $record) {
    $rows[] = array(
      l($record->title, 'node/' . $record->nid),
      check_plain($record->view_count),
      format_date($record->last_viewed),
    );
  }

  // Column headers for the table.
  $header = array(t('Node Title'), t('Views'), t('Last Viewed'));

  // Return a renderable array.
  $output = array();
  $output['table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );
  return $output;
}


/**
 * Implements hook_token_info().
 */
function databasics_token_info() {
  $info = array();

  $info['types'] = array(
    'databasics-totals' => array(
      'name' => t('Databasics totals'),
      'description' => t('Global databasics tokens.'),
    ),
    // [databasics-page:]
    'databasics-page' => array(
      'name' => t('Databasics'),
      'description' => t('Tokens for databasics page counts.'),
      'needs-data' => array('databasics_record'),
    ),
  );

  $info['tokens'] = array(
    'databasics-totals' => array(
      // [databasics-totals:count]
      'count' => array(
        'name' => t('Total page views'),
        'description' => t('Total page views for entire site.'),
      ),
    ),
    // Page specific tokens.
    'databasics-page' => array(
      // Add a token for the view count.
      // [databasics-page:view-count]
      'view-count' => array(
        'name' => t('View count'),
        'description' => t('Number of times the page has been viewed by the current user.'),
      ),
      // [databasics-page:last-viewed]
      'last-viewed' => array(
        'name' => t('Last viewed'),
        'description' => t('Date the page was last viewed.'),
      ),
    ),
  );

  // [node:view-count], [node:view-count:last-viewed]
  $info['tokens']['node'] = array(
    'view-count' => array(
      'name' => t('View count'),
      'description' => t('Number of times the current node has been viewed by the current user.'),
      'type' => 'databasics-page', 
    ),
  );

  return $info;
}



















