
<div class="block-subscribe-wrapper">
    <div class="container">
        <div class="row">
            <div class="span12">
                <?php echo $this->getChildHtml('newsletter') ?>
            </div>
        </div>
    </div>
</div>

<div class="before-footer">
    <div class="container">

        <div class="row">
            <div class="span12">

                <div class="site_social_share">
                    <span class='st_social_text_custom' st_title="<?php echo Mage::app()->getStore()->getFrontendName(); ?>" st_url="<?php echo Mage::getBaseUrl();?>" displayText='Share the Abbott Store'>Share the Abbott Store</span>
                    <span class='st_facebook_custom' st_title="<?php echo Mage::app()->getStore()->getFrontendName(); ?>" st_url="<?php echo Mage::getBaseUrl();?>" displayText='Share with Facebook'><strong>Facebook</strong></span>
                    <span class='st_twitter_custom' st_title="<?php echo Mage::app()->getStore()->getFrontendName(); ?>" st_url="<?php echo Mage::getBaseUrl();?>" displayText='Share with Twitter'><strong>Twitter</strong></span>
                    <span class='st_email_custom' st_title="<?php echo Mage::app()->getStore()->getFrontendName(); ?>" st_url="<?php echo Mage::getBaseUrl();?>" displayText='Share with Email'><strong>Email</strong></span>
                </div>

            </div>
        </div>

    </div>
</div>