<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="row products-grid">
        <?php endif ?>
            <li class="span4 item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <span class="view-overlay">View</span>
					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" width="300" height="300" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
				
			    <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                
                <?php
                $price_html = "<span class=\"price\">";
                if($_product->getSpecialPrice()):
                    $price_html .= "<span class='old-price'>";
                    $price_html .= Mage::helper('core')->currency($_product->getPrice(), true, false);
                    $price_html .= "</span>";
                    $price_html .= "<span class=\"special-price\">";
                    $price_html .= Mage::helper('core')->currency($_product->getSpecialPrice(), true, false);
                    $price_html .= "</span>";
                else:
                    $price_html .= Mage::helper('core')->currency($_product->getPrice(), true, false);
                endif;
                $price_html .= "</span>";
                ?>

                <?php $product_name = strip_tags($_product->getName()) ?>

                <?php if(strlen($product_name)>45) : ?>
                    <?php $product_name = substr($product_name,0,90); ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-name"><?php echo $product_name; ?>&#133; </a>
                    <?php echo $price_html; ?>
                <?php else : ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-name"><?php echo $product_name ?> </a>
                    <?php echo $price_html; ?>
                <?php endif; ?>
                
                 
              

            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>
