<div class="span3 discount-block">
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount">
        <div class="discount-form cf">
            <input type="hidden" name="remove" id="remove-coupone" value="0" />    
            <div class="discount-input-wrapper">
                <div class="input-box">
                    <input class="input-text" id="coupon_code" name="coupon_code" placeholder="Discount Code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                </div>
                <div class="buttons-set">
                    <?php if(strlen($this->getCouponCode())): ?>
                    <button type="button" class="coupon-cancel" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><?php echo $this->__('Cancel Coupon') ?></button>
                    <?php else:?>
                    <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    <?php endif;?>
                </div>
            </div>

        </div>
    </div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
