<?php
// $Id$

/**
 * @file
 * Adds an AJAX based "quick view" link to content.
 */

/**
 * Implementation of hook_menu().
 */
function quickview_menu() {
  $items = array();
  //%node - magic loader loads the node obj
  $items['node/%node/quickview'] = array(
    'page callback' => 'quickview_node',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'delivery callback' => 'ajax_deliver',  //https://api.drupal.org/api/drupal/modules%21system%21system.module/function/system_menu/7.x
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_node_view_alter().
 */
function quickview_node_view_alter(&$build) {
  // Only add the quickview link if the readmore link is there.
  if (isset($build['links']['node']['#links']['node-readmore'])) {
    $nid = $build['#node']->nid;

    // Add the AJAX JavaScript library to our link gets processed.
    drupal_add_library('system', 'drupal.ajax');

    // Add the quickview link.
    $build['links']['quickview']['#theme'] = 'links__quicklinks';
    $build['links']['quickview']['#attached']['js']['misc/ajax.js'] = array('weight' => JS_LIBRARY + 2); //Make sure this is loaded 
    $build['links']['quickview']['#attributes']['class'] = array('links', 'inline');
    $build['links']['quickview']['#links']['quickview'] = array(
      'title' => '↓ Quick view',
      'href' => 'node/' . $nid . '/quickview/nojs', //Check if there's ajax. If there is ajax, nojs will be replace by ajax
      'attributes' => array('class' => array('use-ajax', 'quickview-' . $nid)), //Triggers the ajax misc/ajax.js
    );
  }
}

/**
 * Menu callback; Show the content of a node for quickview.
 */
function quickview_node($node, $mode = NULL) {
  // If the mode is not AJAX, redirect to the normal view of the page.
  if ($mode != 'ajax') {
    drupal_goto('node/' . $node->nid);
  }

  // Create the node "renderable" array.
  $content = node_view($node);

  // Remove the wrapper theming from around the node display and hide comments/links.
  unset($content['#theme']); 
  hide($content['comments']);
  hide($content['links']);

  // Render the HTML of the node.
  $html = render($content);

  // Send the AJAX commands to the calling page.
  $commands = array();
  $commands[] = ajax_command_html('#node-' . $node->nid . ' .content', $html);//Insert/replace the html specidific dom
  $commands[] = ajax_command_remove('.quickview-' . $node->nid );
  //https://api.drupal.org/api/drupal/includes%21ajax.inc/group/ajax_commands/7.x
  // NOTE: this API changed after the recording of the video
  // "ajax_commands" is now "ajax" for the #type property
  // and the "#ajax_commands"" property should now be "#commands"
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}


