<!--
    Start of DoubleClick Floodlight Tag: Please do not remove
    Activity name of this tag: Abbott_StoreFloodlightTag
    URL of the webpage where the tag is expected to be placed: http://store.gregabbott.com
    This tag must be placed between the <body> and </body> tags, as close as possible to the opening tag.
    Creation Date: 06/04/2014
    -->
    <script type="text/javascript">
    var axel = Math.random() + "";
    var a = axel * 10000000000000;
    document.write('<img src="https://ad.doubleclick.net/activity;src=4307244;type=sitet-;cat=Abbot000;ord=' + a + '?" width="1" height="1" alt=""/>');
    </script>
    <noscript>
    <img src="https://ad.doubleclick.net/activity;src=4307244;type=sitet-;cat=Abbot000;ord=1?" width="1" height="1" alt=""/>
    </noscript>
<!-- End of DoubleClick Floodlight Tag: Please do not remove -->
