version: '3.7'



services:
   db:
      image: mysql:8.0
      container_name: appsDB
      volumes:
        - ./data:/var/lib/mysql
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_USER: jmariano
        MYSQL_PASSWORD: T0psecret!
        MYSQL_ROOT_PASSWORD: T0psecret!
        MYSQL_DATABASE: default_schema

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8890:80'
      environment:
        PMA_HOST: db


   #appserver:
      # Configuration for building the docker image for the backend service
      #image: boilerplate:1.0
      #container_name: springboot
      #ports:
        #- "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
      #depends_on: 
        #- db # This service depends on mysql. Start that first.
      #environment: # Pass environment variables to the service
        #SPRING_DATASOURCE_URL: jdbc:mysql://db:6603/webupps?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        #SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:6603/webupps?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        #SPRING_DATASOURCE_USERNAME: webuppsuser
       # SPRING_DATASOURCE_PASSWORD: T0psecret! 
      #networks: # Networks to join (Services on the same network can communicate with each other using their name)
        #- backend
   #working
   #appserver:
      #image: boilerplateinternal:1.0
      #container_name: springboot
      #restart: on-failure
      #depends_on:
        #- db
      #ports:
        #- 8080:8080

        
   
